### ISSUE TITLE
個別問題　特定の動画で途中でエラー

### ISSUE THREAD

**Issue by orz-** [Saccubus/SaccubusFront_Python#14]
766 :名無しさん＠お腹いっぱい。2014/12/12(金) 13:35:45.26 ID:egVtzNBa0
>>765
亀レスすいません
ttp://www.nicovideo.jp/watch/sm5874514
こちらの動画です。
私もデフォルト設定で試みたのですが
どうしても落ちてしまいます。 

767 名前： ◆G/QKMfn152 [sage] 投稿日：2014/12/13(土) 10:32:06.81 ID:AVrT7F4E0
>>766
こちらでも 3時間26分時点（動画長は3時間38分)でエラーとなりffmpegが停止しました。（プレミアムアカウント）
調べてみたのですがエラーメッセージがよくわからないのでψさんに報告しておきます。
動画のコメントを見るとブラウザでもちゃんと再生できない人がいるみたいですが。
蛇足ですがさきゅばす1.50（>>601）でｆｐｓ変換して25fpsにすると最後までコメント付きに変換できましたが
2.0b4が20分（で停止）の所1.50では1時間かかりました。コメントXMLは異常はないようです。

**Comment by orz-** [comment]
前にも報告したかもしれませんが　ちょっと回答を覚えていないので　もう一度登録しておきます。

**Comment by ledyba** [comment]
ブラウザでもちゃんと再生できない事があるなら「変な動画ファイルだったね」で放置で良い気がするんですが、どうでしょう

**Comment by orz-** [comment]
分かりました。
その中にも書いてある通り前に報告したことを覚えてなかったので
登録したのですが放置という結論で了解です。

**Comment by ledyba** [comment]
ぞい
