### ISSUE TITLE
2ch掲示板の要望要約

### ISSUE THREAD

**Issue by orz-** [Saccubus/SaccubusFront_Python#3]
1.nmsgコメントサーバ変換エラー(次で詳述)(優先度大)
2.エラー時の中断で小休止して次の登録動画を変換に進む(優先度大)
2a.　および後でリトライ
3.低画質画像の場合の動画ファイル目印(ファイル名をlowつけにするとか)(優先度大)
3a.　低画質でも次の動画へ行って後で(時間待ちして)リトライ
　（土日休日でも午前２時から午前6時までは低画質回避できそうです。平日は2時から午前中まで大丈夫そう）
4.#754(#801) chrome loginと(#920)＃922 input same sizeのソース取り込み（優先度大） 
5.ファイル名の書式を指定通りにしたい
6.上限・下限解像度と入力動画の解像度を比べて自動調整機能がほしい　FPSも同様
7.個別問題#767 #774
8.vo-aac→内蔵aacオプション(およびffmpeg)変更　（jenkinsのffmpegは内蔵AACになっている）

**Comment by orz-** [comment]
nmsgサーバで変換エラーの起こる動画　sm27018502 
キン肉マン　マッスルファイト　ボス２必殺技集
192秒
プレミアム接続コメントサーバー　nmsg
一般アカウント接続コメントサーバー　nmsg
使ったffmpegはhttp://www1.axfc.net/u/3569388.zip　ですがたぶんffmpegは関係ないかと
エラー状況は２種類あってどちらが起こるかは分かりません。
1つ目のセットは原因がよくわからないですが接続しただけで動画ダウンロードも失敗します。
2つ目のセットは Http BAD Requestで　1.xxで起こったのと同じメッセージでした。
今回は2つ目の方が起こせなかったので動画をあらかじめダウンロードして
わざと起こしました。（状況的に動画ダウンロード後に起こるので）
2chの方に貼られたログも BAD Requestでした。

以下のログでメールアドレス　パスワード　ユーザーIDは変更しました。

__log__launcher.log

Launching Saccubus......
executing
[sm27018502] executing => ext\ffmpeg\bin\ffmpeg.exe -y -f saccubus  -minfps 25  -sacc sm27018502#--warning#--resolve-comment-back#500#--plugin-deploy#simple#--ng-script#.\ng-script\mymemOK.py#--plugin-font#simple#--resolve-cookie#firefox#--resolve-password#MYPASSWORD#--resolve-resource-path#.\__download__#--resolve-user#myaccount@gmail.com -i ext\Saccubus\Saccubus.dll -strict -2 -acodec copy -vcodec libx264 -coder 1 -f mp4 -pix_fmt yuv420p     ".\__download__/sm27018502_conv_キン肉マン　マッスルファイト　ボス２必殺技集.mp4"
[sm27018502] executed

sm27018502__log__.log

executing... 
ext\ffmpeg\bin\ffmpeg.exe -y -f saccubus  -minfps 25  -sacc sm27018502#--warning#--resolve-comment-back#500#--plugin-deploy#simple#--ng-script#.\ng-script\mymemOK.py#--plugin-font#simple#--resolve-cookie#firefox#--resolve-password#MYPASSWORD#--resolve-resource-path#.\__download__#--resolve-user#myaccount@gmail.com -i ext\Saccubus\Saccubus.dll -strict -2 -acodec copy -vcodec libx264 -coder 1 -f mp4 -pix_fmt yuv420p     ".\__download__/sm27018502_conv_キン肉マン　マッスルファイト　ボス２必殺技集.mp4"  
result: 
ffmpeg version git-2015-11-19-bbaa282 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 5.2.0 (GCC)
  configuration: --arch=x86 --target-os=mingw32 --cross-prefix=/home/orz/desktop/saccubus/ffmpeg-windows-build-helpers/sandbox/mingw-w64-i686/bin/i686-w64-mingw32- --pkg-config=pkg-config --disable-w32threads --enable-gpl --enable-libsoxr --enable-fontconfig --enable-libass --enable-libutvideo --enable-libbluray --enable-iconv --enable-libtwolame --extra-cflags=-DLIBTWOLAME_STATIC --enable-libzvbi --enable-libcaca --enable-libmodplug --extra-libs=-lstdc++ --extra-libs=-lpng --enable-libvidstab --enable-libx265 --enable-decklink --extra-libs=-loleaut32 --enable-libx264 --enable-libxvid --enable-libmp3lame --enable-version3 --enable-zlib --enable-librtmp --enable-libvorbis --enable-libtheora --enable-libspeex --enable-libopenjpeg --enable-gnutls --enable-libgsm --enable-libfreetype --enable-libopus --enable-frei0r --enable-filter=frei0r --enable-libvo-aacenc --enable-bzlib --enable-libxavs --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroedinger --enable-libvpx --enable-libilbc --enable-libwavpack --enable-libwebp --enable-libgme --enable-dxva2 --enable-libdcadec --enable-avisynth --enable-gray --extra-libs=-lpsapi --extra-cflags=-static-libgcc --enable-static --disable-shared --prefix=/home/orz/desktop/saccubus/ffmpeg-windows-build-helpers/sandbox/mingw-w64-i686/i686-w64-mingw32 --enable-runtime-cpudetect
  libavutil      55.  6.100 / 55.  6.100
  libavcodec     57. 15.100 / 57. 15.100
  libavformat    57. 15.100 / 57. 15.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 15.100 /  6. 15.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
[saccubus indev @ 050ead20] Initializing...
[saccubus indev @ 050ead20] arg[ 0]=> ext\Saccubus\Saccubus.dll
[saccubus indev @ 050ead20] arg[ 1]=> sm27018502
[saccubus indev @ 050ead20] arg[ 2]=> --warning
[saccubus indev @ 050ead20] arg[ 3]=> --resolve-comment-back
[saccubus indev @ 050ead20] arg[ 4]=> 500
[saccubus indev @ 050ead20] arg[ 5]=> --plugin-deploy
[saccubus indev @ 050ead20] arg[ 6]=> simple
[saccubus indev @ 050ead20] arg[ 7]=> --ng-script
[saccubus indev @ 050ead20] arg[ 8]=> .\ng-script\mymemOK.py
[saccubus indev @ 050ead20] arg[ 9]=> --plugin-font
[saccubus indev @ 050ead20] arg[ 10]=> simple
[saccubus indev @ 050ead20] arg[ 11]=> --resolve-cookie
[saccubus indev @ 050ead20] arg[ 12]=> firefox
[saccubus indev @ 050ead20] arg[ 13]=> --resolve-password
[saccubus indev @ 050ead20] arg[ 14]=> MYPASSWORD
[saccubus indev @ 050ead20] arg[ 15]=> --resolve-resource-path
[saccubus indev @ 050ead20] arg[ 16]=> .\__download__
[saccubus indev @ 050ead20] arg[ 17]=> --resolve-user
[saccubus indev @ 050ead20] arg[ 18]=> myaccount@gmail.com
[W][ PluginOrganizer] Unknwon config: (deploy) = (simple)
[W][ PluginOrganizer] Unknwon config: (font) = (simple)
[E][    PyBridgeImpl] Python says: 
Traceback (most recent call last):
  File D:\saccubus\Saccubus2.0b4\ext\SaccubusFront\src\saccubus\resource\resolve.py, 36, in fromNative
  File D:\saccubus\Saccubus2.0b4\ext\SaccubusFront\src\saccubus\resource\resolve.py, 130, in download
  File D:\saccubus\Saccubus2.0b4\ext\SaccubusFront\src\saccubus\net\video.py, 32, in downloadVideo
AttributeError: 'NoneType' object has no attribute 'split'
[E][    PyBridgeImpl] Failed to run: <function fromNative at 0x0597C420>
Saccubus exception caught: (in ..\..\src\saccubus\python\PyBridgeImpl.cpp:329): Failed to run: <function fromNative at 0x0597C420>
[Saccubus FFmpeg Adapter] An error has occurred. Press [ENTER] to continue.
[saccubus indev @ 050ead20] Failed to configure adapter.
ext\Saccubus\Saccubus.dll: Operation not permitted

sm27018502_meta_info.xml

<?xml version="1.0" encoding="UTF-8"?>
<nicovideo_thumb_response status="ok">
  <thumb>
    <video_id>sm27018502</video_id>
    <cache>icon</cache>
    <title>キン肉マン　マッスルファイト　ボス２必殺技集</title>
    <description>08/16に別バージョンが公開された「ボス２ver.2」の必殺技・超必殺技を紹介します。※CPU専用キャラ。従来のバージョンも継続して公開されていますので、好きな方を選べます。本編の必殺技集はコチラから：mylist/13557472</description>
    <thumbnail_url>http://tn-skr3.smilevideo.jp/smile?i=27018502</thumbnail_url>
    <first_retrieve>2015-08-26T17:17:12+09:00</first_retrieve>
    <length>3:12</length>
    <movie_type>mp4</movie_type>
    <size_high>14365479</size_high>
    <size_low>9859147</size_low>
    <view_counter>8786</view_counter>
    <comment_num>125</comment_num>
    <mylist_counter>31</mylist_counter>
    <last_res_body>傲岸不遜っぷりの表現 ガンマン人気投票トッ クリスマス限定あやつ 死んでる人もありなら 変身後のは足が好きだ </last_res_body>
    <watch_url>http://www.nicovideo.jp/watch/sm27018502</watch_url>
    <thumb_type>video</thumb_type>
    <embeddable>1</embeddable>
    <no_live_play>1</no_live_play>
    <tags domain="jp">
      <tag category="1" lock="1">ゲーム</tag>
      <tag lock="1">キン肉マン</tag>
      <tag lock="1">マッスルファイト</tag>
      <tag lock="1">ゲームエフェクト集</tag>
      <tag>完璧超人始祖</tag>
      <tag>ガンマン</tag>
      <tag>私は変身などしなーい！</tag>
    </tags>
    <user_id>567267</user_id>
    <user_nickname>aoi_russian</user_nickname>
    <user_icon_url>http://usericon.nimg.jp/usericon/s/56/567267.jpg?1401373667</user_icon_url>
  </thumb>
</nicovideo_thumb_response>

sm27018502_play_info.txt

thread_id=1440577033&l=192&url=http%3A%2F%2Fsmile-fnl51.nicovideo.jp%2Fsmile%3Fm%3D27018502.51325&ms=http%3A%2F%2Fnmsg.nicovideo.jp%2Fapi%2F&ms_sub=http%3A%2F%2Fnmsg.nicovideo.jp%2Fapi%2F&user_id=MYID&is_premium=0&nickname=%E3%81%8A%E5%85%84&time=1455187673821&done=true&ng_rv=1&hms=hiroba.nicovideo.jp&hmsp=2620&hmst=960&hmstk=1455187733.mi5GVYATEjk6NcGMs_tUniCOeCI&userkey=99999999999.%7E1%7ETnN6GlhHW6EqY2BKEeP5q-VPMMsLe3OPHD76wUWhPGg


今回は2つ目の方が起こせなかったので動画をあらかじめダウンロードして
わざと起こしました。（状況的に動画ダウンロード後に起こるので）

__log__launcher.log

Launching Saccubus......
executing
[sm27018502] executing => ext\ffmpeg\bin\ffmpeg.exe -y -f saccubus -minfps 25   -sacc sm27018502#--resolve-user#MYACCOUNT@gmail.com#--resolve-password#MYPASSWORD#--resolve-cookie#own#--resolve-resource-path#.\__download__#--ng-script#.\ng-script\mymemOK.py#--plugin-deploy#simple#--resolve-comment-back#500#--plugin-font#simple#--warning -i ext\Saccubus\Saccubus.dll -strict -2 -acodec copy -vcodec libx264 -coder 1 -f mp4 -pix_fmt yuv420p     ".\__download__/sm27018502_conv_キン肉マン　マッスルファイト　ボス２必殺技集.mp4"
[sm27018502] executed

sm27018502__log__.log

executing... 
ext\ffmpeg\bin\ffmpeg.exe -y -f saccubus -minfps 25   -sacc sm27018502#--resolve-user#MYACCOUNT@gmail.com#--resolve-password#MYPASSWORD#--resolve-cookie#own#--resolve-resource-path#.\__download__#--ng-script#.\ng-script\mymemOK.py#--plugin-deploy#simple#--resolve-comment-back#500#--plugin-font#simple#--warning -i ext\Saccubus\Saccubus.dll -strict -2 -acodec copy -vcodec libx264 -coder 1 -f mp4 -pix_fmt yuv420p     ".\__download__/sm27018502_conv_キン肉マン　マッスルファイト　ボス２必殺技集.mp4"  
result: 
ffmpeg version git-2015-11-19-bbaa282 Copyright (c) 2000-2015 the FFmpeg developers
  built with gcc 5.2.0 (GCC)
  configuration: --arch=x86 --target-os=mingw32 --cross-prefix=/home/orz/desktop/saccubus/ffmpeg-windows-build-helpers/sandbox/mingw-w64-i686/bin/i686-w64-mingw32- --pkg-config=pkg-config --disable-w32threads --enable-gpl --enable-libsoxr --enable-fontconfig --enable-libass --enable-libutvideo --enable-libbluray --enable-iconv --enable-libtwolame --extra-cflags=-DLIBTWOLAME_STATIC --enable-libzvbi --enable-libcaca --enable-libmodplug --extra-libs=-lstdc++ --extra-libs=-lpng --enable-libvidstab --enable-libx265 --enable-decklink --extra-libs=-loleaut32 --enable-libx264 --enable-libxvid --enable-libmp3lame --enable-version3 --enable-zlib --enable-librtmp --enable-libvorbis --enable-libtheora --enable-libspeex --enable-libopenjpeg --enable-gnutls --enable-libgsm --enable-libfreetype --enable-libopus --enable-frei0r --enable-filter=frei0r --enable-libvo-aacenc --enable-bzlib --enable-libxavs --enable-libopencore-amrnb --enable-libopencore-amrwb --enable-libvo-amrwbenc --enable-libschroedinger --enable-libvpx --enable-libilbc --enable-libwavpack --enable-libwebp --enable-libgme --enable-dxva2 --enable-libdcadec --enable-avisynth --enable-gray --extra-libs=-lpsapi --extra-cflags=-static-libgcc --enable-static --disable-shared --prefix=/home/orz/desktop/saccubus/ffmpeg-windows-build-helpers/sandbox/mingw-w64-i686/i686-w64-mingw32 --enable-runtime-cpudetect
  libavutil      55.  6.100 / 55.  6.100
  libavcodec     57. 15.100 / 57. 15.100
  libavformat    57. 15.100 / 57. 15.100
  libavdevice    57.  0.100 / 57.  0.100
  libavfilter     6. 15.100 /  6. 15.100
  libswscale      4.  0.100 /  4.  0.100
  libswresample   2.  0.101 /  2.  0.101
  libpostproc    54.  0.100 / 54.  0.100
[saccubus indev @ 0096ace0] Initializing...
[saccubus indev @ 0096ace0] arg[ 0]=> ext\Saccubus\Saccubus.dll
[saccubus indev @ 0096ace0] arg[ 1]=> sm27018502
[saccubus indev @ 0096ace0] arg[ 2]=> --resolve-user
[saccubus indev @ 0096ace0] arg[ 3]=> MYACCOUNT@gmail.com
[saccubus indev @ 0096ace0] arg[ 4]=> --resolve-password
[saccubus indev @ 0096ace0] arg[ 5]=> MYPASSWORD
[saccubus indev @ 0096ace0] arg[ 6]=> --resolve-cookie
[saccubus indev @ 0096ace0] arg[ 7]=> own
[saccubus indev @ 0096ace0] arg[ 8]=> --resolve-resource-path
[saccubus indev @ 0096ace0] arg[ 9]=> .\__download__
[saccubus indev @ 0096ace0] arg[ 10]=> --ng-script
[saccubus indev @ 0096ace0] arg[ 11]=> .\ng-script\mymemOK.py
[saccubus indev @ 0096ace0] arg[ 12]=> --plugin-deploy
[saccubus indev @ 0096ace0] arg[ 13]=> simple
[saccubus indev @ 0096ace0] arg[ 14]=> --resolve-comment-back
[saccubus indev @ 0096ace0] arg[ 15]=> 500
[saccubus indev @ 0096ace0] arg[ 16]=> --plugin-font
[saccubus indev @ 0096ace0] arg[ 17]=> simple
[saccubus indev @ 0096ace0] arg[ 18]=> --warning
[W][ PluginOrganizer] Unknwon config: (deploy) = (simple)
[W][ PluginOrganizer] Unknwon config: (font) = (simple)
[E][    PyBridgeImpl] Python says: 
Traceback (most recent call last):
  File D:\saccubus\Saccubus2.0b4\ext\SaccubusFront\src\saccubus\resource\resolve.py, 36, in fromNative
  File D:\saccubus\Saccubus2.0b4\ext\SaccubusFront\src\saccubus\resource\resolve.py, 130, in download
  File D:\saccubus\Saccubus2.0b4\ext\SaccubusFront\src\saccubus\net\thread.py, 30, in downloadThreads
  File D:\saccubus\Saccubus2.0b4\ext\SaccubusFront\src\saccubus\net\thread.py, 38, in downloadThread
  File D:\saccubus\Saccubus2.0b4\ext\python3\lib\urllib\request.py, 451, in open
  File D:\saccubus\Saccubus2.0b4\ext\python3\lib\urllib\request.py, 580, in http_response
  File D:\saccubus\Saccubus2.0b4\ext\python3\lib\urllib\request.py, 494, in error
  File D:\saccubus\Saccubus2.0b4\ext\python3\lib\urllib\request.py, 440, in _call_chain
  File D:\saccubus\Saccubus2.0b4\ext\python3\lib\urllib\request.py, 594, in http_error_default
HTTPError: HTTP Error 400: Bad Request
[E][    PyBridgeImpl] Failed to run: <function fromNative at 0x0597C420>
Saccubus exception caught: (in ..\..\src\saccubus\python\PyBridgeImpl.cpp:329): Failed to run: <function fromNative at 0x0597C420>
[Saccubus FFmpeg Adapter] An error has occurred. Press [ENTER] to continue.
[saccubus indev @ 0096ace0] Failed to configure adapter.
ext\Saccubus\Saccubus.dll: Operation not permitted

sm27018502_meta_info.xml

<?xml version="1.0" encoding="UTF-8"?>
<nicovideo_thumb_response status="ok">
  <thumb>
    <video_id>sm27018502</video_id>
    <cache>icon</cache>
    <title>キン肉マン　マッスルファイト　ボス２必殺技集</title>
    <description>08/16に別バージョンが公開された「ボス２ver.2」の必殺技・超必殺技を紹介します。※CPU専用キャラ。従来のバージョンも継続して公開されていますので、好きな方を選べます。本編の必殺技集はコチラから：mylist/13557472</description>
    <thumbnail_url>http://tn-skr3.smilevideo.jp/smile?i=27018502</thumbnail_url>
    <first_retrieve>2015-08-26T17:17:12+09:00</first_retrieve>
    <length>3:12</length>
    <movie_type>mp4</movie_type>
    <size_high>14365479</size_high>
    <size_low>9859147</size_low>
    <view_counter>8786</view_counter>
    <comment_num>125</comment_num>
    <mylist_counter>31</mylist_counter>
    <last_res_body>傲岸不遜っぷりの表現 ガンマン人気投票トッ クリスマス限定あやつ 死んでる人もありなら 変身後のは足が好きだ </last_res_body>
    <watch_url>http://www.nicovideo.jp/watch/sm27018502</watch_url>
    <thumb_type>video</thumb_type>
    <embeddable>1</embeddable>
    <no_live_play>1</no_live_play>
    <tags domain="jp">
      <tag category="1" lock="1">ゲーム</tag>
      <tag lock="1">キン肉マン</tag>
      <tag lock="1">マッスルファイト</tag>
      <tag lock="1">ゲームエフェクト集</tag>
      <tag>完璧超人始祖</tag>
      <tag>ガンマン</tag>
      <tag>私は変身などしなーい！</tag>
    </tags>
    <user_id>567267</user_id>
    <user_nickname>aoi_russian</user_nickname>
    <user_icon_url>http://usericon.nimg.jp/usericon/s/56/567267.jpg?1401373667</user_icon_url>
  </thumb>
</nicovideo_thumb_response>

sm27018502_play_info.txt

thread_id=1440577033&l=192&url=http%3A%2F%2Fsmile-fnl51.nicovideo.jp%2Fsmile%3Fm%3D27018502.51325&ms=http%3A%2F%2Fnmsg.nicovideo.jp%2Fapi%2F&ms_sub=http%3A%2F%2Fnmsg.nicovideo.jp%2Fapi%2F&user_id=MYID&is_premium=0&nickname=%E3%81%8A%E5%85%84&time=1455188859524&done=true&ng_rv=1&hms=hiroba.nicovideo.jp&hmsp=2532&hmst=80&hmstk=1455188919.Dk-vIH6cZ0gWTc7stcuoRrU_4Tk&userkey=1455190659.%7E1%7EXntPvuFqcddWueOwlFatyG3U6v5KY1bawLA3ZjwFvdU

**Comment by orz-** [comment]
掲示板生ログ（関係部分）
(やたらと細かい注文する人がいますがどうやら1系でも細かい注文をつける人と同一人物らしく
　通報動画で変換できないといってきたので登録年齢が未成年者のようです。
　成人年齢(18歳以上)で登録していれば通報動画かどうかは分かりません。通常と同じ)

http://potato.2ch.net/test/read.cgi/software/1346798166/754

754 名前：名無しさん＠お腹いっぱい。[sage] 投稿日：2014/11/09(日) 16:07:06.30 ID:euYNgiPX0
ext\SaccubusFront\src\saccubus\net\login\chrome.py を弄って
最新 Chrome に対応させてみた。
https://gist.github.com/anonymous/9c416ffded5683d06672

【ニコニコ】コメント付動画作成ツール さきゅばす
http://potato.2ch.net/test/read.cgi/software/1346798166/767

767 名前： ◆G/QKMfn152 [sage] 投稿日：2014/12/13(土) 10:32:06.81 ID:AVrT7F4E0
>>766
こちらでも 3時間26分時点（動画長は3時間38分)でエラーとなりffmpegが停止しました。（プレミアムアカウント）
調べてみたのですがエラーメッセージがよくわからないのでψさんに報告しておきます。
動画のコメントを見るとブラウザでもちゃんと再生できない人がいるみたいですが。
蛇足ですがさきゅばす1.50（>>601）でｆｐｓ変換して25fpsにすると最後までコメント付きに変換できましたが
2.0b4が20分（で停止）の所1.50では1時間かかりました。コメントXMLは異常はないようです。


【ニコニコ】コメント付動画作成ツール さきゅばす
http://potato.2ch.net/test/read.cgi/software/1346798166/774

774 名前：771[sage] 投稿日：2015/01/25(日) 21:15:35.70 ID:bzLq6BMQ0
>>772
そういう質問したのも以下の動画を2.0b4でエンコードすると
http://www.nicovideo.jp/watch/sm999686
コメントがどうしてもカクカク流れるんよ。
※recipeはau_win__4_3.pyを使用

同梱されてるffmpegが原因かなと思ったんだけどどうなんだろう？


【ニコニコ】コメント付動画作成ツール さきゅばす
http://potato.2ch.net/test/read.cgi/software/1346798166/801

801 名前：名無しさん＠お腹いっぱい。[sage] 投稿日：2015/03/01(日) 10:38:39.88 ID:NFtx28+30
>>754
遅くなって大変失礼いたしました。確認しようとして頭から飛んでしまっていました。
以下ご案内
chrome バージョン 40.0.2214.115 m (64-bit) でログイン確認いたしました。 win7 home
VIRUS TOTAL 検査問題なし　検出率　0 / 57
https://www.virustotal.com/ja/file/a955ae7da79f46b0620aa3105a09c27240312cc9e820e1cdd8550d9afad210b5/analysis/1425171232/
>>754のURLページの右側ダウンロードボタンからDLできますが tar.gz 形式なので対応した解凍ソフトを使って展開して
ext\SaccubusFront\src\saccubus\net\login\chrome.py に上書きして下さい。


【ニコニコ】コメント付動画作成ツール さきゅばす
http://potato.2ch.net/test/read.cgi/software/1346798166/870

870 名前：名無しさん＠お腹いっぱい。[sage] 投稿日：2015/08/10(月) 20:00:03.06 ID:DkyNnJEu0
さきゅばす２で
読みに行って低画質モードだったら10分待ってリトライを繰り返す、みたいな機能を追加できないかな
それかせめて低画質だったらこれは低画質だったと分かる機能がほしい


【ニコニコ】コメント付動画作成ツール さきゅばす
http://potato.2ch.net/test/read.cgi/software/1346798166/873

873 名前：名無しさん＠お腹いっぱい。[sage] 投稿日：2015/08/14(金) 13:23:52.91 ID:ziEJ/hda0
２系にソースと同じ解像度でコメント動画を生成させるオプションがほしい


【ニコニコ】コメント付動画作成ツール さきゅばす
http://potato.2ch.net/test/read.cgi/software/1346798166/876

876 名前：名無しさん＠お腹いっぱい。[sage] 投稿日：2015/08/18(火) 12:32:39.61 ID:Y/Ko/Nw60
>>870
低画質モードになるかならないかは動画によるので
１つに引っかかってもそこでずっと足踏みするんでなく
ウェイトを挟んで次の動画に処理を移すようにした方がいい
そしてリストの最後まで行ったら頭に戻って巡回すればいい

>>875
ぜひお願いします
自分は今の2みたいにPython製でソースが目に見えてるから保存するファイル名の命名規則ぐらいなら素人でもすぐいじれる状態が好きだ、
ということも伝えていただければと。

【ニコニコ】コメント付動画作成ツール さきゅばす
http://potato.2ch.net/test/read.cgi/software/1346798166/922

922 名前：名無しさん＠お腹いっぱい。[sage] 投稿日：2015/09/22(火) 18:26:36.48 ID:felsW42H0
>>921
おっと、失礼しました。インデント消えてしまってました
いちおrecipeファイルをアップローダのほうにも上げておきました。

http://www1.axfc.net/uploader/so/3538019




【ニコニコ】コメント付動画作成ツール さきゅばす
http://potato.2ch.net/test/read.cgi/software/1346798166/923

923 名前：名無しさん＠お腹いっぱい。[sage] 投稿日：2015/09/23(水) 00:59:12.00 ID:rxIqrfhH0
Saccubus2.0b4は新しいコメントサーバーに対応することはある予定でしょうか？

【ニコニコ】コメント付動画作成ツール さきゅばす
http://potato.2ch.net/test/read.cgi/software/1346798166/927

927 名前：名無しさん＠お腹いっぱい。[] 投稿日：2015/09/29(火) 19:48:02.50 ID:6g/CvG+W0
俺も２系の方が好きだし使い慣れてるから２系の更新が続いてほしい…

とりあえず欲しい機能

１．新コメントサーバーに対応
２．低画質モード時は処理を止め、高画質モードになるまで待つ機能
３．２が無理なら、低画質でDLされたファイルにはファイル名に目印を付ける機能
４．コマンドラインウインドウでエラーが出た時、入力待ちを無限にせず、１分程度のウエイトを置いて次の動画に移る機能

【ニコニコ】コメント付動画作成ツール さきゅばす
http://potato.2ch.net/test/read.cgi/software/1346798166/938

938 名前：名無しさん＠お腹いっぱい。[sage] 投稿日：2015/10/16(金) 16:21:17.58 ID:8FNKTT/u0
２系に欲しい機能
１．低画質モード時は処理をせず、高画質になるまで待つ機能
２．１が無理なら、低画質でDLされたファイルにはファイル名に目印を付ける機能
３． 画面サイズ同じ＆音声無エンコで変換(>>922
４．コマンドラインウインドウでエラーが出た際、入力待ちを無限にせず１分程度のウエイトで次の動画に処理を移す機能
５．ファイル名の書式を指定したい。動画名、うp者名、タグ、動画説明文も盛り込みたい。
６．解像度・FPS指定は、それぞれオリジナル動画が指定数値以上だったらオリジナル動画の数値を維持し、指定数値未満だったら指定数値に上げるという挙動をして欲しい。
７．１系にも２系みたいな複数の動画を処理予定リストに入れて順次処理する機能
８．欲を言えば処理予定リストのレジューム機能（リストに残りがある状態で途中で終了すると次回は前回のリストの状態を復元）。

**Comment by ledyba** [comment]
申し訳ないんですが、機能ごとに必要かどうか議論して実装してcloseするというワークフローにしたいので、分けてもらえないでしょうか

**Comment by orz-** [comment]
項目を分けて再度全部登録しなおします。失礼しました

**Comment by ledyba** [comment]
全部個別のIssueにコピペされたっぽいのでcloseします
