### ISSUE TITLE
要望：低画質画像の場合の動画ファイル目印(ファイル名とか)

### ISSUE THREAD

**Issue by orz-** [Saccubus/SaccubusFront_Python#7]
http://potato.2ch.net/test/read.cgi/software/1346798166/870

870 名前：名無しさん＠お腹いっぱい。[sage] 投稿日：2015/08/10(月) 20:00:03.06 ID:DkyNnJEu0
さきゅばす２で
読みに行って低画質モードだったら10分待ってリトライを繰り返す、みたいな機能を追加できないかな
それかせめて低画質だったらこれは低画質だったと分かる機能がほしい

876 名前：名無しさん＠お腹いっぱい。[sage] 投稿日：2015/08/18(火) 12:32:39.61 ID:Y/Ko/Nw60
>>870
低画質モードになるかならないかは動画によるので
１つに引っかかってもそこでずっと足踏みするんでなく
ウェイトを挟んで次の動画に処理を移すようにした方がいい
そしてリストの最後まで行ったら頭に戻って巡回すればいい

>>875
ぜひお願いします
自分は今の2みたいにPython製でソースが目に見えてるから保存するファイル名の命名規則ぐらいなら素人でもすぐいじれる状態が好きだ、
ということも伝えていただければと。

927 名前：名無しさん＠お腹いっぱい。[] 投稿日：2015/09/29(火) 19:48:02.50 ID:6g/CvG+W0
俺も２系の方が好きだし使い慣れてるから２系の更新が続いてほしい…

とりあえず欲しい機能

１．(省略)
２．(省略)
３．２が無理なら、低画質でDLされたファイルにはファイル名に目印を付ける機能
４．(省略)

**Comment by ledyba** [comment]
#12 とmergeして良い気がするけど、これもプレミアム会員になると解決する問題ですね
https://secure.nicovideo.jp/payment/registration?site=&next_url=

**Comment by ledyba** [comment]
これもプレミアム会員になれば解決する問題なので閉じます
