### ISSUE TITLE
要望：低画質でも次の動画へ行って後で(時間待ちして)リトライ 

### ISSUE THREAD

**Issue by orz-** [Saccubus/SaccubusFront_Python#8]
土日休日でも午前２時から午前6時までは低画質回避できそうです。平日は2時から午前中まで大丈夫そう
http://potato.2ch.net/test/read.cgi/software/1346798166/

870 名前：名無しさん＠お腹いっぱい。[sage] 投稿日：2015/08/10(月) 20:00:03.06 ID:DkyNnJEu0
さきゅばす２で
読みに行って低画質モードだったら10分待ってリトライを繰り返す、みたいな機能を追加できないかな
それかせめて低画質だったらこれは低画質だったと分かる機能がほしい

927 名前：名無しさん＠お腹いっぱい。[] 投稿日：2015/09/29(火) 19:48:02.50 ID:6g/CvG+W0
俺も２系の方が好きだし使い慣れてるから２系の更新が続いてほしい…

とりあえず欲しい機能

１．(省略)
２．低画質モード時は処理を止め、高画質モードになるまで待つ機能
３．(省略)
４．(省略)

**Comment by ledyba** [comment]
プレミアム会員っていうのになると解決する問題だと思うんですけど（名推理）
https://secure.nicovideo.jp/payment/registration?site=&next_url=

**Comment by ledyba** [comment]
プレミアム会員になると解決する問題なので閉じます
